#!/usr/bin/python

import sys, random

terms = {
    "Activity" : "A distinct, scheduled portion of work performed during the course of a project",
    "Activity Code" : "An alphanumeric value assigned to each activity that enables classifying, sorting, and filtering",
    "Activity Identifier" : "A unique alphanumeric value assigned to an activity and used to differentiate that activity from other activities",
    "Activity Label" : "A phrase that names and describes an activity",
    "Actual Cost" : "The realized cost incurred for the work performed on an activity during a specific time period",
    "Analogous Estimating" : "A technique for estimating the duration or cost of an activity or a project using historical data from a similar activity or project",
    "Apportioned Effort" : "An activity where effort is allotted proportionately across certain discrete efforts and not divisible into discrete efforts",
    "Assumption" : "A factor in the planning process considered to be true, real, or certain, without proof or demonstration",
    "Backward Pass" : "A critical path method technique for calculating the late start and late finish dates by working backward through the schedule model from the project end date",
    "Baseline" : "The approved version of a work product that can be changed using formal change control procedures and is used as the basis for comparison to actual results",
    "Bottom-Up Estimating" : "A method of estimating project duration or cost by aggregating the estimates of the lower-level components of the work breakdown structure",
    "Budget at Completion" : "The sum of all budgets established for the work to be performed",
    "Change Control" : "A process whereby modifications to documents, deliverables, or baselines associated with the project are identified, documented, approved, or rejected",
    "Change Control Board" : "A formally chartered group responsible for reviewing, evaluating, approving, delaying, or rejecting changes to the project, and for recording and communicating such decisions",
    "Change Control System" : "A set of procedures that describes how modifications to the project deliverables and documentation are managed and controlled",
    "Change Request" : "A formal proposal to modify a document, deliverable, or baseline",
    "Code of Accounts" : "A numbering system used to uniquely identify each component of the work breakdown structure",
    "Communications Management Plan" : "A component of the project, program, or portfolio management plan that describes how, when, and by whom information will be administered and disseminated",
    "Configuration Management System" : "A collection of procedures used to track project artifacts and monitor and control changes to these artifacts",
    "Constraint" : "A factor that limits the options for managing a project, program, portfolio, or process",
    "Contingency Plan" : "A document describing actions that the project team can take if predetermined trigger conditions occur",
    "Contingency Reserve" : "Time or money allocated in the schedule or cost baseline for known risks with active response strategies",
    "Control Account" : "A management control point where scope, budget, actual cost, and schedule are integrated and compared to earned value for performance measurement",
    "Corrective Action" : "An intentional activity that realigns the performance of the project work with the project management plan",
    "Cost Baseline" : "The approved version of work package cost estimates and contingency reserve that can be changed using formal change control procedures and is used as the basis for comparison to actual results",
    "Cost Management Plan" : "A component of a project or program management plan that describes how costs will be planned, structured, and controlled",
    "Cost Performance Index" : "A measure of the cost efficiency of budgeted resources expressed as the ratio of earned value to actual cost",
    "Cost Variance" : "The amount of budget deficit or surplus at a given point in time, expressed as the difference between the earned value and the actual cost",
    "Crashing" : "A schedule compression technique used to shorten the schedule duration for the least incremental cost by adding resources",
    "Critical Chain Method" : "A schedule method that allows the project team to place buffers on any project schedule path to account for limited resources and project uncertainties",
    "Critical Path" : "The sequence of activities that represents the longest path through a project, which determines the shortest possible duration" ,
    "Critical Path Activity" : "Any activity on the critical path in a project schedule",
    "Critical Path Method" : "A method used to estimate the minimum project duration and determine the amount of scheduling flexibility on the logical network paths within the schedule model" ,
    "Data Date" : "A point in time when the status of the project is recorded" ,
    "Decision Tree Analysis" : "A diagramming and calculation technique for evaluating the implications of a chain of multiple options in the presence of uncertainty" ,
    "Decomposition" : "A technique used for dividing and subdividing the project scope and project deliverables into smaller, more manageable parts" ,    
    "Defect Repair" : "An intentional activity to modify a nonconforming product or product component" ,
    "Deliverable" : "Any unique and verifiable product, result, or capability to perform a service that is produced to complete a process, phase, or project" ,
    "Discrete Effort" : "An activity that can be planned and measured and that yields a specific output" ,
    "Duration" : "The total number of work periods required to complete an activity or work breakdown structure component, expressed in hours, days, or weeks" ,
    "Early Finish Date" : "In the critical path method, the earliest possible point in time when the uncompleted portions of a schedule activity can finish based on the schedule network logic, the data date, and any schedule constraints" ,
    "Early Start Date" : "In the critical path method, the earliest possible point in time when the uncompleted portions of a schedule activity can start based on the schedule network logic, the data date, and any schedule constraints" ,
    "Earned Value" : "The measure of work performed expressed in terms of the budget authorized for that work" ,
    "Earned Value Management" : "A methodology that combines scope, schedule, and resource measurements to assess project performance and progress" ,
    "Effort" : "The number of labor units required to complete a schedule activity or work breakdown structure component, often expressed in hours, days, or weeks" ,
    "Enterprise Environmental Factors" : "Conditions, not under the immediate control of the team, that influence, constrain, or direct the project, program, or portfolio" ,
    "Estimate at Completion" : "The expected total cost of completing all work expressed as the sum of the actual cost to date and the estimate to complete" ,
    "Estimate to Complete" : "The expected cost to finish all the remaining project work" ,
    "Fast Tracking" : "A schedule compression technique in which activities or phases normally done in sequence are performed in parallel for at least a portion of their duration" ,
    "Finish-to-Finish" : "A logical relationship in which a successor activity cannot finish until a predecessor activity has finished" ,
    "Finish-to-Start" : "A logical relationship in which a successor activity cannot start until a predecessor activity has finished" ,
    "Fixed Formula Method" : "A method of estimating earned value in which a specified percentage of the budget value of a work package is assigned to the start milestone and the remaining percentage is assigned when the work package is complete" ,
    "Forward Pass" : "A critical path method technique for calculating the early start and early finish dates by working forward through the schedule model from the project start date or a given point in time" ,
    "Free Float" : "The amount of time that a schedule activity can be delayed without delaying the early start date of any successor or violating a schedule constraint" ,
    "Functional Organization" : "An organizational structure in which staff is grouped by areas of specialization and the project manager has limited authority to assign work and apply resources" ,
    "Gantt Chart" : "A bar chart of schedule information where activities are listed on the vertical axis, dates are shown on the horizontal axis, and activity durations are shown as horizontal bars placed according to start and finish dates" ,
    "Lag" : "The amount of time whereby a successor activity will be delayed with respect to a predecessor activity" ,
    "Late Finish Date" : "In the critical path method, the latest possible point in time when the uncompleted portions of a schedule activity can finish based on the schedule network logic, the project completion date, and any schedule constraints" ,
    "Late Start Date" : "In the critical path method, the latest possible point in time when the uncompleted portions of a schedule activity can start based on the schedule network logic, the project completion date, and any schedule constraints" ,
    "Lead" : "The amount of time whereby a successor activity can be advanced with respect to a predecessor activity" ,
    "Lessons Learned" : "The knowledge gained during a project which shows how project events were addressed or should be addressed in the future for the purpose of improving future performance" ,
    "Level of Effort" : "An activity that does not produce definitive end products and is measured by the passage of time" ,
    "Logical Relationship" : "A dependency between two activities or between an activity and a milestone" ,
    "Management Reserve" : "Time or money that management sets aside in addition to the schedule or cost baseline and releases for unforeseen work that is within the scope of the project" ,
    "Matrix Organization" : "An organizational structure in which the project manager shares authority with the functional manager temporarily to assign work and apply resources" ,
    "Milestone" : "A significant point or event in a project, program, or portfolio" ,
    "Milestone Schedule" : "A type of schedule that presents milestones with planned dates" ,
    "Most Likely Duration" : "An estimate of the most probable activity duration that takes into account all of the known variables that could affect performance" ,
    "Near-Critical Activity" : "An activity with a total float that is deemed to be low based on expert judgment" ,
    "Near-Critical Path" : "A sequence of activities with low float which, if exhausted, becomes a critical path sequence for the project" ,
    "Network Logic" : "All activity dependencies in a project schedule network diagram" ,
    "Network Path" : "A sequence of activities connected by logical relationships in a project schedule network diagram" ,
    "Node" : "A point at which dependency lines connect on a schedule network diagram" ,
    "Opportunity" : "A risk that would have a positive effect on one or more project objectives" ,
    "Optimistic Duration" : "An estimate of the shortest activity duration that takes into account all of the known variables that could affect performance" ,
    "Organizational Breakdown Structure" : "A hierarchical representation of the project organization, which illustrates the relationship between project activities and the organizational units that will perform those activities" ,
    "Organizational Enabler" : "A structural, cultural, technological, or human-resource practice that the performing organization can use to achieve strategic objectives" ,
    "Organizational Process Assets" : "Plans, processes, policies, procedures, and knowledge bases specific to and used by the performing organization" ,
    "Organizational Project Management" : "A framework in which portfolio, program, and project management are integrated with organizational enablers in order to achieve strategic objectives" ,
    "Organizational Project Management Maturity" : "The level of an organization’s ability to deliver the desired strategic outcomes in a predictable, controllable, and reliable manner" ,
    "Parametric Estimating" : "An estimating technique in which an algorithm is used to calculate cost or duration based on historical data and project parameters" ,
    "Path Convergence" : "A relationship in which a schedule activity has more than one predecessor" ,
    "Path Divergence" : "A relationship in which a schedule activity has more than one successor" ,
    "Percent Complete" : "An estimate expressed as a percent of the amount of work that has been completed on an activity or a work breakdown structure component" ,
    "Performance Measurement Baseline" : "Integrated scope, schedule, and cost baselines used for comparison to manage, measure, and control project execution" ,
    "Performing Organization" : "An enterprise whose personnel are the most directly involved in doing the work of the project or program" ,
    "Pessimistic Duration" : "An estimate of the longest activity duration that takes into account all of the known variables that could affect performance" ,
    "Phase Gate" : "A review at the end of a phase in which a decision is made to continue to the next phase, to continue with modification, or to end a project or program" ,
    "Planned Value" : "The authorized budget assigned to scheduled work" ,
    "Portfolio" : "Projects, programs, subsidiary portfolios, and operations managed as a group to achieve strategic objectives" ,
    "Portfolio Balancing" : "The process of optimizing the mix of portfolio components to further the strategic objectives of the organization" ,
    "Portfolio Charter" : "A document issued by a sponsor that authorizes and specifies the portfolio structure and links the portfolio to the organization’s strategic objectives" ,
    "Portfolio Management" : "The centralized management of one or more portfolios to achieve strategic objectives" ,
    "Portfolio Management Plan" : "A document that specifies how a portfolio will be organized, monitored, and controlled" ,
    "Portfolio Manager" : "The person or group assigned by the performing organization to establish, balance, monitor, and control portfolio components in order to achieve strategic business objectives" ,
    "Precedence Diagramming Method" : "A technique used for constructing a schedule model in which activities are represented by nodes and are graphically linked by one or more logical relationships to show the sequence in which the activities are to be performed" ,
    "Predecessor Activity" : "An activity that logically comes before a dependent activity in a schedule" ,
    "Preventive Action" : "An intentional activity that ensures the future performance of the project work is aligned with the project management plan" ,
    "Probability and Impact Matrix" : "A grid for mapping the probability of occurrence of each risk and its impact on project objectives if that risk occurs" ,
    "Procurement Management Plan" : "A component of the project or program management plan that describes how a team will acquire goods and services from outside of the performing organization" ,
    "Product Life Cycle" : "The series of phases that represent the evolution of a product, from concept through delivery, growth, maturity, and to retirement" ,
    "Program" : "Related projects, subsidiary programs, and program activities managed in a coordinated manner to obtain benefits not available from managing them individually" ,
    "Program Charter" : "A document issued by a sponsor that authorizes the program management team to use organizational resources to execute the program and links the program to the organization’s strategic objectives" ,
    "Program Evaluation and Review Technique" : "A technique used to estimate project duration through a weighted average of optimistic, pessimistic, and most likely activity durations when there is uncertainty with the individual activity estimates" ,
    "Program Management" : "The application of knowledge, skills, and principles to a program to achieve the program objectives and to obtain benefits and control not available by managing program components individually" ,
    "Program Management Office" : "A management structure that standardizes the program-related governance processes and facilitates the sharing of resources, methodologies, tools, and techniques" ,
    "Program Management Plan" : "A document that integrates the program’s subsidiary plans and establishes the management controls and overall plan for integrating and managing the program’s individual components" ,
    "Program Manager" : "The person authorized by the performing organization to lead the team or teams responsible for achieving program objectives" ,
    "Progressive Elaboration" : "The iterative process of increasing the level of detail in a project management plan as greater amounts of information and more accurate estimates become available" ,
    "Project" : "A temporary endeavor undertaken to create a unique product, service, or result" ,
    "Project Budget" : "The sum of work package cost estimates, contingency reserve, and management reserve" ,
    "Project Calendar" : "A calendar that identifies working days and shifts that are available for scheduled activities" ,
    "Project Charter" : "A document issued by the project initiator or sponsor that formally authorizes the existence of a project and provides the project manager with the authority to apply organizational resources to project activities" ,
    "Project Life Cycle" : "The series of phases that a project passes through from its start to its completion" ,
    "Project Management" : "The application of knowledge, skills, tools, and techniques to project activities to meet the project requirements" ,
    "Project Management Office" : "A management structure that standardizes the project-related governance processes and facilitates the sharing of resources, methodologies, tools, and techniques" ,
    "Project Management Plan" : "The document that describes how the project will be executed, monitored and controlled, and closed" ,
    "Project Manager" : "The person assigned by the performing organization to lead the team that is responsible for achieving the project objectives" ,
    "Project Phase" : "A collection of logically related project activities that culminates in the completion of one or more deliverables" ,
    "Project Schedule" : "An output of a schedule model that presents linked activities with planned dates, durations, milestones, and resources" ,
    "Project Schedule Network Diagram" : "A graphical representation of the logical relationships among the project schedule activities" ,
    "Project Scope" : "The work performed to deliver a product, service, or result with the specified features and functions" ,
    "Project Scope Statement" : "The description of the project scope, major deliverables, assumptions, and constraints" ,
    "Projectized Organization" : "An organizational structure in which the project manager has full authority to assign work and apply resources" ,
    "Quality Management Plan" : "A component of the project or program management plan that describes how an organization’s policies, procedures, and guidelines will be implemented to achieve the quality objectives" ,
    "Requirements Management Plan" : "A component of the project or program management plan that describes how requirements will be analyzed, documented, and managed" ,
    "Requirements Traceability Matrix" : "A grid that links product requirements from their origin to the deliverables that satisfy them" ,
    "Residual Risk" : "The risk that remains after risk responses have been implemented" ,
    "Resource Breakdown Structure" : "A hierarchical representation of resources by category and type" ,
    "Resource Calendar" : "A calendar that identifies the working days and shifts upon which each specific resource is available" ,
    "Resource Leveling" : "A resource optimization technique in which adjustments are made to the project schedule to optimize the allocation of resources and which may affect critical path" ,
    "Resource Management Plan" : "A component of the project management plan that describes how project resources are acquired, allocated, monitored, and controlled" ,
    "Resource Optimization Technique" : "A technique in which activity start and finish dates are adjusted to balance demand for resources with the available supply" ,
    "Resource Smoothing" : "A resource optimization technique in which free and total float are used without affecting the critical path" ,
    "Responsibility Assignment Matrix" : "A grid that shows the project resources assigned to each work package" ,
    "Risk" : "An uncertain event or condition that, if it occurs, has a positive or negative effect on one or more project objectives" ,
    "Risk Acceptance" : "A risk response strategy whereby the project team decides to acknowledge the risk and not take any action unless the risk occurs" ,
    "Risk Appetite" : "The degree of uncertainty an organization or individual is willing to accept in anticipation of a reward" ,
    "Risk Avoidance" : "A risk response strategy whereby the project team acts to eliminate the threat or protect the project from its impact" ,
    "Risk Breakdown Structure" : "A hierarchical representation of potential sources of risk" ,
    "Risk Category" : "A group of potential causes of risk" ,
    "Risk Enhancement" : "A risk response strategy whereby the project team acts to increase the probability of occurrence or impact of an opportunity" ,
    "Risk Exploiting" : "A risk response strategy whereby the project team acts to ensure that an opportunity occurs" ,
    "Risk Exposure" : "An aggregate measure of the potential impact of all risks at any given point in time in a project, program, or portfolio" ,
    "Risk Management Plan" : "A component of the project, program, or portfolio management plan that describes how risk management activities will be structured and performed" ,
    "Risk Mitigation" : "A risk response strategy whereby the project team acts to decrease the probability of occurrence or impact of a threat" ,
    "Risk Owner" : "The person responsible for monitoring the risk and for selecting and implementing an appropriate risk response strategy" ,
    "Risk Register" : "A repository in which outputs of risk management processes are recorded" ,
    "Risk Sharing" : "A risk response strategy whereby the project team allocates ownership of an opportunity to a third party who is best able to capture the benefit for the project" ,
    "Risk Threshold" : "The measure of acceptable variation around an objective that reflects the risk appetite of the organization and stakeholders" ,
    "Risk Transference" : "A risk response strategy whereby the project team shifts the impact of a threat to a third party, together with ownership of the response" ,
    "Rolling Wave Planning" : "An iterative planning technique in which the work to be accomplished in the near term is planned in detail, while the work in the future is planned at a higher level" ,
    "Schedule Baseline" : "The approved version of a schedule model that can be changed using formal change control procedures and is used as the basis for comparison to actual results" ,
    "Schedule Compression" : "A technique used to shorten the schedule duration without reducing the project scope" ,
    "Schedule Management Plan" : "A component of the project or program management plan that establishes the criteria and the activities for developing, monitoring, and controlling the schedule" ,
    "Schedule Model" : "A representation of the plan for executing the project’s activities, including durations, dependencies, and other planning information, used to produce a project schedule along with other scheduling artifacts" ,
    "Schedule Model Analysis" : "A process used to investigate or analyze the output of the schedule model in order to optimize the schedule" ,
    "Schedule Network Analysis" : "A technique to identify early and late start dates, as well as early and late finish dates, for the uncompleted portions of project activities" ,
    "Schedule Performance Index" : "A measure of schedule efficiency expressed as the ratio of earned value to planned value" ,
    "Schedule Variance" : "A measure of schedule performance expressed as the difference between the earned value and the planned value" ,
    "Scope Baseline" : "The approved version of a scope statement, work breakdown structure (WBS), and its associated WBS dictionary that can be changed using formal change control procedures and is used as the basis for comparison to actual results" ,
    "Scope Creep" : "The uncontrolled expansion to product or project scope without adjustments to time, cost, and resources" ,
    "Scope Management Plan" : "A component of the project or program management plan that describes how the scope will be defined, developed, monitored, controlled, and validated" ,
    "S-Curve Analysis" : "A technique used to indicate performance trends by using a graph that displays cumulative costs over a specific time period" ,
    "Secondary Risk" : "A risk that arises as a direct result of implementing a risk response" ,
    "Sponsor" : "An individual or a group that provides resources and support for the project, program, or portfolio, and is accountable for enabling success" ,
    "Staffing Management Plan" : "A component of the resource management plan that describes when and how team members will be acquired and how long they will be needed" ,
    "Stakeholder" : "An individual, group, or organization that may affect, be affected by, or perceive itself to be affected by a decision, activity, or outcome of a project, program, or portfolio" ,
    "Stakeholder Engagement Plan" : "A component of the project or program management plan that identifies the strategies and actions required to promote productive involvement of stakeholders in project or program decision making and execution" ,
    "Start-to-Finish" : "A logical relationship in which a successor activity cannot finish until a predecessor activity has started" ,
    "Start-to-Start" : "A logical relationship in which a successor activity cannot start until a predecessor activity has started" ,
    "Successor Activity" : "A dependent activity that logically comes after another activity in a schedule" ,
    "Summary Activity" : "A group of related schedule activities aggregated and displayed as a single activity" ,
    "Threat" : "A risk that would have a negative effect on one or more project objectives" ,
    "Three-Point Estimating" : "A technique used to estimate cost or duration by applying an average or weighted average of optimistic, pessimistic, and most likely estimates when there is uncertainty with the individual activity estimates" ,
    "To-Complete Performance Index" : "A measure of the cost performance that is achieved with the remaining resources in order to meet a specified management goal, expressed as the ratio of the cost to finish the outstanding work to the remaining budget" ,
    "Total Float" : "The amount of time that a schedule activity can be delayed or extended from its early start date without delaying the project finish date or violating a schedule constraint" ,
    "Trigger Condition" : "An event or situation that indicates that a risk is about to occur" ,
    "Variance Analysis" : "A technique for determining the cause and degree of difference between the baseline and actual performance" ,
    "Variance at Completion" : "A projection of the amount of budget deficit or surplus, expressed as the difference between the budget at completion and the estimate at completion" ,
    "WBS Dictionary" : "A document that provides detailed deliverable, activity, and scheduling information about each component in the work breakdown structure" ,
    "Weighted Milestone Method" : "A method of estimating earned value in which the budget value of a work package is divided into measurable segments, each ending with a milestone that is assigned a weighted budget value" ,
    "What-If Scenario Analysis" : "The process of evaluating scenarios in order to predict their effect on project objectives" ,
    "Work Breakdown Structure" : "A hierarchical decomposition of the total scope of work to be carried out by the project team to accomplish the project objectives and create the required deliverables" ,
    "Work Package" : "The work defined at the lowest level of the work breakdown structure for which cost and duration are estimated and managed" ,
    "Workaround" : "An immediate and temporary response to an issue, for which a prior response had not been planned or was not effective"
}

terms2 = {
    "1": "one",
    "2": "two",
    "3": "three",
    "4": "four"
}

queue = list()

for (term, text) in terms.items():
    queue.append((term, text))

random.seed()
random.shuffle(queue)
nr_total = 0
nr_correct = 0

while len(queue) > 0:
    try:
        (term, text) = queue.pop(0);
        answer = input(text + "\n")
        nr_total = nr_total + 1
        if answer.strip().upper() == term.strip().upper():
            print("OK\n")
            nr_correct = nr_correct + 1
        else:
            print("FAILED! Correct - '" + term + "'\n")
            queue.insert(random.randint(10,20), (term, text))
    except KeyboardInterrupt:
        print("Exiting\n");
        print("Success Rate = " + str(nr_correct * 100 / nr_total) + "%\n")
        sys.exit(0);
